<a href="https://colab.research.google.com/github/OmarNoussier/Data-Analysis-and-Predictive-Modeling/blob/main/Checkpoint1_Data_Cleaning_Omar_Noussier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1: Introduction**
I will manage all project responsibilities independently, including data research, analysis, visualization, and report writing. I will ensure a structured approach to handling tasks effectively and efficiently. My project will be centered on predicting customer loss for an online retailer.

My key questions will include:
1.   How do purchase frequency and discount usage correlate with retention?
2.   What strategies can the company use to retain high-value customers?
3.   What customer behaviors indicate a high risk of churn?

Understanding customer retention is crucial for business growth, and e-commerce companies can enhance customer engagement and revenue by comprehending churn behaviors. This dataset provides valuable transactional data, enabling
insightful analysis into purchasing behaviors and retention strategies.

# **Part 2: Load your Dataset**

In [ ]:
# Upload the dataset file into Colab
from google.colab import files
uploaded = files.upload()

Saving E-commerce Dataset.csv to E-commerce Dataset.csv

In [ ]:
# Read the dataset
import pandas as pd
df = pd.read_csv('E-commerce Dataset.csv')

In [ ]:
# View some records form the dataset
df.head()

,Order_Date,Time,Aging,Customer_Id,Gender,Device_Type,Customer_Login_type,Product_Category,Product,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Payment_method
0,2018-01-02,1900-01-01 10:56:33,8.0,37077,Female,Web,Member,Auto & Accessories,Car Media Players,140.0,1.0,0.3,46.0,4.6,Medium,credit_card
1,2018-07-24,1900-01-01 20:41:37,2.0,59173,Female,Web,Member,Auto & Accessories,Car Speakers,211.0,1.0,0.3,112.0,11.2,Medium,credit_card
2,2018-11-08,1900-01-01 08:38:49,8.0,41066,Female,Web,Member,Auto & Accessories,Car Body Covers,117.0,5.0,0.1,31.2,3.1,Critical,credit_card
3,2018-04-18,1900-01-01 19:28:06,7.0,50741,Female,Web,Member,Auto & Accessories,Car & Bike Care,118.0,1.0,0.3,26.2,2.6,High,credit_card
4,2018-08-13,1900-01-01 21:18:39,9.0,53639,Female,Web,Member,Auto & Accessories,Tyre,250.0,1.0,0.3,160.0,16.0,Critical,credit_card

In [ ]:
# View the information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Date           51290 non-null  object
 1   Time                 51290 non-null  object
 2   Aging                51289 non-null  float64
 3   Customer_Id          51290 non-null  int64
 4   Gender               51290 non-null  object
 5   Device_Type          51290 non-null  object
 6   Customer_Login_type  51290 non-null  object
 7   Product_Category     51290 non-null  object
 8   Product              51290 non-null  object
 9   Sales                51289 non-null  float64
 10  Quantity             51288 non-null  float64
 11  Discount             51289 non-null  float64
 12  Profit               51290 non-null  float64
 13  Shipping_Cost        51289 non-null  float64
 14  Order_Priority       51288 non-null  object
 15  Payment_method       51290 non-null  object
dtypes: float64(6), int64(1), object(9)
memory usage: 6.3+ MB

In [ ]:
# Describe the Dataset
df.describe()

,Aging,Customer_Id,Sales,Quantity,Discount,Profit,Shipping_Cost
count,51289.000000,51290.000000,51289.000000,51288.000000,51289.000000,51290.000000,51289.000000
mean,5.255035,58155.758764,152.340872,2.502983,0.303821,70.407226,7.041557
std,2.959948,26032.215826,66.495419,1.511859,0.131027,48.729488,4.871745
min,1.000000,10000.000000,33.000000,1.000000,0.100000,0.500000,0.100000
25%,3.000000,35831.250000,85.000000,1.000000,0.200000,24.900000,2.500000
50%,5.000000,61018.000000,133.000000,2.000000,0.300000,59.900000,6.000000
75%,8.000000,80736.250000,218.000000,4.000000,0.400000,118.400000,11.800000
max,10.500000,99999.000000,250.000000,5.000000,0.500000,167.500000,16.800000

# Observations on Initial Issues in the Dataset:
1.   Missing Values: Several columns, including Aging, Sales, Quantity, Discount, Shipping_Cost, and Order_Priority, have missing values that need to be handled.
2.   Data Type Issues: Order_Date and Time are stored as object (string) types instead of datetime, which may affect time-based analysis.
3. Potential Outliers: The Quantity and Profit columns have wide value ranges, indicating potential outliers that should be examined further.

## **Part 3: Perform a 5-Step Data Cleaning Process**

In [ ]:
# Verify the missing values
df.isnull().sum()

Order_Date             0
Time                   0
Aging                  1
Customer_Id            0
Gender                 0
Device_Type            0
Customer_Login_type    0
Product_Category       0
Product                0
Sales                  1
Quantity               2
Discount               1
Profit                 0
Shipping_Cost          1
Order_Priority         2
Payment_method         0
dtype: int64

In [ ]:
# Convert 'Order_Date' to datetime format
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [ ]:
# Convert 'Time' to datetime format
df['Time'] = pd.to_datetime(df['Time'])

In [ ]:
# Identify and Remove Duplicates
df.drop_duplicates(inplace=True)

In [ ]:
# Create a boxplot for dataset using Plotly
import plotly.express as px
fig = px.box(df, y=['Quantity', 'Profit'])
fig.show()

In [ ]:
# Identify records with unrealistic values
unrealistic_values = df[
    (df['Sales'] < 0) |
    (df['Quantity'] < 0) |
    (df['Profit'] < 0) |
    (df['Discount'] < 0) |
    (df['Shipping_Cost'] < 0)]

# Analysis of Extreme Values (Outliers):
From the box plot, we observe that the Quantity has very little variation, the Profit shows a significant spread with a wide interquartile range (IQR) and some extreme values extending far above the whiskers.
High-profit outliers can skew summary statistics, affecting analysis and decision-making. Proper handling involves keeping high-profit transactions for accurate insights or removing extreme values for rare anomalies.

## **Step 4: Answer at Least One Descriptive Analytics Question**

Observations from the Chart:
*   The scatter plot shows the relationship between purchase frequency (how often a customer makes a purchase) and discount usage (amount of discount applied per purchase).

*   There is no strong visible trend suggesting a clear correlation between frequent buyers and higher discount usage.

*   Some customers with low purchase frequency have received high discounts, while others with higher purchase frequency still received moderate discounts.

*   This suggests that discounts alone may not be a major driver of retention and other factors (such as customer experience, product value, or loyalty programs) could be influencing repeat purchases.

# **Step 5: Export Cleaned Dataset for Tableau**

In [ ]:
# Create the CSV file
df.to_csv('E-commerce Dataset.csv', index=False)

In [ ]:
# Download to the desktop
from google.colab import files
files.download('E-commerce Dataset.csv')